site_name: TOTVS Fluig - Grupo Décio
repo_url: https://github.com/grupoDecio/docs
repo_name: grupoDecio
edit_uri: edit/main/docs
nav:
  - Inicio: index.md
  - Guidelines:
    - 'Guia do Iniciante': 'guidelines/begginers_guide.md'
  - Datasets:
    - 'Genérico': 'datasets/ds_generico.md'
  - Repository:
    - 'GitHub': 'repository/github.md'
  - Sobre: about.md
theme:
  logo: img/favicon.ico
  name: material
  nav_style: dark

plugins:
  - git-revision-date
  - search
