site_name: TOTVS Fluig - Grupo Décio
repo_url: https://github.com/grupoDecio/docs
repo_name: grupoDecio
edit_uri: edit/main/docs
nav:
  - Inicio: index.md
  - Guidelines:
      - "Guia do iniciante": "guidelines/begginers_guide.md"
      - "Guia de configuração de processos GIT": "guidelines/fluig-git_guide.md"
      - "Guia de configuração da documentação": "guidelines/mkdocs_guide.md"
  - Datasets:
      - "Genérico": "datasets/ds_generico.md"
      - "Usuários por grupo": "datasets/dsUsuariosPorGrupo.md"
  - Repositório:
      - "GitHub": "repository/github.md"
  - Mapeamento:
      - "Grupos e papéis": "mapping/grupos-papeis.md"
      - "Banco de dados FLUIG": "mapping/banco-dados-fluig.md"
  - Funções:
      - "Validação por grupo": "functions/validaPorGrupo.md"
  - Sobre: about.md
theme:
  logo: img/favicon.ico
  name: material
  nav_style: dark

plugins:
  - git-revision-date
  - search
  - git-authors
