site_name: TOTVS Fluig - Grupo Décio
nav:
  - Inicio: index.md
  - Guidelines:
    - 'Guia do Iniciante': 'guidelines/begginers_guide.md'
  - Datasets:
    - 'Genérico': 'datasets/ds_generico.md'
  - Repository:
    - 'GitHub': 'repository/github.md'
  - Sobre: about.md
theme:
  logo: img/favicon.ico
  name: readthedocs
  nav_style: dark
